<a href="https://colab.research.google.com/github/AnindyaNaura12/Data-Mining/blob/main/labu_price.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [87]:
from google.colab import files
uploaded = files.upload()

Saving pumpkin price.csv to pumpkin price (2).csv

In [112]:
data = pd.read_csv("pumpkin price.csv")
data.head()

,Commodity Name,City Name,Type,Package,Variety,Sub Variety,Grade,Date,Low Price,High Price,...,Color,Environment,Unit of Sale,Quality,Condition,Appearance,Storage,Crop,Repack,Trans Mode
0,PUMPKINS,NEW YORK,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,09/24/2016,150,170,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
1,PUMPKINS,NEW YORK,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,09/24/2016,150,170,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
2,PUMPKINS,NEW YORK,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,09/24/2016,130,150,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
3,PUMPKINS,NEW YORK,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,09/24/2016,130,150,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
4,PUMPKINS,NEW YORK,NaN,36 inch bins,HOWDEN TYPE,NaN,NaN,09/24/2016,120,140,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN

In [113]:
data.info()
data.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112 entries, 0 to 111
Data columns (total 25 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Commodity Name   112 non-null    object
 1   City Name        112 non-null    object
 2   Type             0 non-null      float64
 3   Package          112 non-null    object
 4   Variety          112 non-null    object
 5   Sub Variety      18 non-null     object
 6   Grade            0 non-null      float64
 7   Date             112 non-null    object
 8   Low Price        112 non-null    int64
 9   High Price       112 non-null    int64
 10  Mostly Low       112 non-null    int64
 11  Mostly High      112 non-null    int64
 12  Origin           112 non-null    object
 13  Origin District  15 non-null     object
 14  Item Size        104 non-null    object
 15  Color            21 non-null     object
 16  Environment      0 non-null      float64
 17  Unit of Sale     25 non-null     object
 18  Quality          0 non-null      float64
 19  Condition        0 non-null      float64
 20  Appearance       0 non-null      float64
 21  Storage          0 non-null      float64
 22  Crop             0 non-null      float64
 23  Repack           112 non-null    object
 24  Trans Mode       0 non-null      float64
dtypes: float64(9), int64(4), object(12)
memory usage: 22.0+ KB

,Type,Grade,Low Price,High Price,Mostly Low,Mostly High,Environment,Quality,Condition,Appearance,Storage,Crop,Trans Mode
count,0.0,0.0,112.000000,112.000000,112.000000,112.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mean,NaN,NaN,107.125000,116.482143,107.312500,116.410714,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,71.840931,77.454664,71.830008,77.545285,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,15.000000,16.000000,15.000000,16.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,18.000000,20.000000,18.000000,18.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,130.000000,140.000000,130.000000,140.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,150.000000,170.000000,150.000000,170.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,260.000000,300.000000,260.000000,300.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [114]:
cat_cols = data.select_dtypes(include=['object']).columns
data = pd.get_dummies(data, columns=cat_cols, drop_first=True)

In [115]:
y = data['High Price']
x = data.drop('High Price', axis=1)

In [116]:
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)

In [120]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression

poly = PolynomialFeatures(degree=2)

In [121]:
model = LinearRegression()
model.fit(x_train_poly, y_train)

LinearRegression()

In [122]:
y_train_pred = model.predict(x_train_poly)
y_test_pred = model.predict(x_test_poly)

In [124]:
rmse_train = np.sqrt(mean_squared_error(y_train, y_train_pred) )
rmse_test = np.sqrt(mean_squared_error(y_test, y_test_pred) )

print("RMSE Training:", rmse_train)
print("RMSE Testing:", rmse_test)

RMSE Training: 8.098077318821163
RMSE Testing: 12.567809797993524