<a href="https://colab.research.google.com/github/AnindyaNaura12/Data-Mining/blob/main/Modul5No3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [43]:
!pip install mlxtend

Requirement already satisfied: mlxtend in /usr/local/lib/python3.12/dist-packages (0.23.4)
Requirement already satisfied: scipy>=1.2.1 in /usr/local/lib/python3.12/dist-packages (from mlxtend) (1.16.3)
Requirement already satisfied: numpy>=1.16.2 in /usr/local/lib/python3.12/dist-packages (from mlxtend) (2.0.2)
Requirement already satisfied: pandas>=0.24.2 in /usr/local/lib/python3.12/dist-packages (from mlxtend) (2.2.2)
Requirement already satisfied: scikit-learn>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from mlxtend) (1.6.1)
Requirement already satisfied: matplotlib>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from mlxtend) (3.10.0)
Requirement already satisfied: joblib>=0.13.2 in /usr/local/lib/python3.12/dist-packages (from mlxtend) (1.5.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (26.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24.2->mlxtend) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24.2->mlxtend) (2025.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.3.1->mlxtend) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->mlxtend) (1.17.0)

In [44]:
import warnings
warnings.filterwarnings("ignore")

import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

In [45]:
from google.colab import files
uploaded = files.upload()

Saving Restaurant.csv to Restaurant (2).csv

In [46]:
df = pd.read_csv("Restaurant.csv")
df.columns = ["BOROUGH", "CUISINE", "GRADE"]
df.head()

       BOROUGH     CUISINE GRADE
0   MANHATTAN    American      C
1       BRONX     Chicken      C
2   MANHATTAN    American      A
3   MANHATTAN    American      A
4   MANHATTAN    American      C

In [47]:
transactions = df.values.tolist()
for t in transactions[:20]:
    print(t)

[' MANHATTAN ', ' American ', ' C']
[' BRONX ', ' Chicken ', ' C']
[' MANHATTAN ', ' American ', ' A']
[' MANHATTAN ', ' American ', ' A']
[' MANHATTAN ', ' American ', ' C']
[' BRONX ', ' Pizza ', ' A']
[' MANHATTAN ', ' Caribbean ', ' B']
[' MANHATTAN ', ' Italian ', ' B']
[' STATENISLAND ', ' Bakery ', ' A']
[' BROOKLYN ', ' Creole ', ' A']
[' MANHATTAN ', ' Chinese ', ' A']
[' MANHATTAN ', ' American ', ' B']
[' QUEENS ', ' American ', ' A']
[' BRONX ', ' Pizza ', ' A']
[' QUEENS ', ' Cafe/Coffee/Tea ', ' A']
[' MANHATTAN ', ' Italian ', ' A']
[' MANHATTAN ', ' Pizza ', ' B']
[' QUEENS ', ' Japanese ', ' B']
[' MANHATTAN ', ' Delicatessen ', ' B']
[' QUEENS ', ' Pizza ', ' A']

In [48]:
te = TransactionEncoder()
te_data = te.fit(transactions).transform(transactions)

df_te = pd.DataFrame(te_data, columns=te.columns_)
df_te.head()

,A,Afghan,African,American,Armenian,Asian,Australian,B,BRONX,BROOKLYN,...,Southwestern,Spanish,Steak,Tapas,Tex-Mex,Thai,Turkish,Vegetarian,Vietnamese/Cambodian/Malaysia,Z
0,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
2,True,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,True,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [87]:
frequent_items = apriori(df_encoded, min_support=0.02, use_colnames=True)
frequent_items

     support                                           itemsets
0   0.513081                                               ( A)
1   0.239164                                       ( American )
2   0.283887                                               ( B)
3   0.095204                                          ( BRONX )
4   0.232744                                       ( BROOKLYN )
5   0.032693                                         ( Bakery )
6   0.156340                                               ( C)
7   0.032120                                ( Cafe/Coffee/Tea )
8   0.030412                                      ( Caribbean )
9   0.118038                                        ( Chinese )
10  0.047672                                        ( Italian )
11  0.032054                                       ( Japanese )
12  0.051895  ( Latin (Cuban Dominican Puerto Rican South & ...
13  0.412647                                      ( MANHATTAN )
14  0.031119                                        ( Mexican )
15  0.055194                                          ( Pizza )
16  0.227080                                         ( QUEENS )
17  0.032326                                   ( STATENISLAND )
18  0.022895                                        ( Spanish )
19  0.036343                                               ( Z)
20  0.134402                                   ( A,  American )
21  0.047655                                      ( BRONX ,  A)
22  0.116414                                   ( A,  BROOKLYN )
23  0.022016                            ( A,  Cafe/Coffee/Tea )
24  0.046264                                    ( Chinese ,  A)
25  0.024492                                    ( A,  Italian )
26  0.020030  ( A,  Latin (Cuban Dominican Puerto Rican Sout...
27  0.214806                                  ( A,  MANHATTAN )
28  0.029450                                      ( A,  Pizza )
29  0.113181                                     ( A,  QUEENS )
30  0.021026                               ( A,  STATENISLAND )
31  0.061208                                   ( B,  American )
32  0.045329                           ( American ,  BROOKLYN )
33  0.034179                                   ( C,  American )
34  0.129867                          ( MANHATTAN ,  American )
35  0.040071                             ( QUEENS ,  American )
36  0.027319                                      ( BRONX ,  B)
37  0.066889                                   ( B,  BROOKLYN )
38  0.041768                                    ( Chinese ,  B)
39  0.113671                                  ( B,  MANHATTAN )
40  0.069120                                     ( B,  QUEENS )
41  0.036727                                   ( C,  BROOKLYN )
42  0.036076                            ( Chinese ,  BROOKLYN )
43  0.023240                                    ( Chinese ,  C)
44  0.066416                                  ( MANHATTAN ,  C)
45  0.034624                                     ( C,  QUEENS )
46  0.029316                           ( Chinese ,  MANHATTAN )
47  0.033673                              ( Chinese ,  QUEENS )
48  0.029394                           ( Italian ,  MANHATTAN )
49  0.025238                       ( A,  American ,  BROOKLYN )
50  0.072642                      ( A,  MANHATTAN ,  American )
51  0.022000                         ( A,  QUEENS ,  American )
52  0.033228                      ( B,  MANHATTAN ,  American )

In [88]:
rules = association_rules(frequent_items, metric="confidence", min_threshold=0.2)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,( A),( American ),0.513081,0.239164,0.134402,0.261950,1.095273,1.0,0.011691,1.030873,0.178645,0.217533,0.029949,0.411957
1,( American ),( A),0.239164,0.513081,0.134402,0.561963,1.095273,1.0,0.011691,1.111595,0.114329,0.217533,0.100392,0.411957
2,( BRONX ),( A),0.095204,0.513081,0.047655,0.500555,0.975588,1.0,-0.001192,0.974921,-0.026912,0.085002,-0.025724,0.296717
3,( A),( BROOKLYN ),0.513081,0.232744,0.116414,0.226891,0.974855,1.0,-0.003003,0.992430,-0.050308,0.184956,-0.007628,0.363535
4,( BROOKLYN ),( A),0.232744,0.513081,0.116414,0.500179,0.974855,1.0,-0.003003,0.974188,-0.032525,0.184956,-0.026496,0.363535
5,( Cafe/Coffee/Tea ),( A),0.032120,0.513081,0.022016,0.685432,1.335915,1.0,0.005536,1.547899,0.259794,0.042081,0.353963,0.364171
6,( Chinese ),( A),0.118038,0.513081,0.046264,0.391940,0.763895,1.0,-0.014299,0.800775,-0.259504,0.079103,-0.248791,0.241054
7,( Italian ),( A),0.047672,0.513081,0.024492,0.513772,1.001348,1.0,0.000033,1.001422,0.001413,0.045672,0.001420,0.280754
8,( Latin (Cuban Dominican Puerto Rican South & ...,( A),0.051895,0.513081,0.020030,0.385976,0.752272,1.0,-0.006596,0.792997,-0.257792,0.036756,-0.261038,0.212507
9,( A),( MANHATTAN ),0.513081,0.412647,0.214806,0.418658,1.014568,1.0,0.003084,1.010341,0.029490,0.302151,0.010235,0.469607
10,( MANHATTAN ),( A),0.412647,0.513081,0.214806,0.520556,1.014568,1.0,0.003084,1.015591,0.024447,0.302151,0.015351,0.469607
11,( Pizza ),( A),0.055194,0.513081,0.029450,0.533569,1.039931,1.0,0.001131,1.043925,0.040641,0.054655,0.042076,0.295483
12,( A),( QUEENS ),0.513081,0.227080,0.113181,0.220591,0.971425,1.0,-0.003329,0.991675,-0.056969,0.180518,-0.008395,0.359505
13,( QUEENS ),( A),0.227080,0.513081,0.113181,0.498420,0.971425,1.0,-0.003329,0.970770,-0.036662,0.180518,-0.030110,0.359505
14,( STATENISLAND ),( A),0.032326,0.513081,0.021026,0.650430,1.267696,1.0,0.004440,1.392910,0.218222,0.040097,0.282079,0.345705
15,( B),( American ),0.283887,0.239164,0.061208,0.215609,0.901508,1.0,-0.006687,0.969970,-0.132368,0.132531,-0.030960,0.235768
16,( American ),( B),0.239164,0.283887,0.061208,0.255926,0.901508,1.0,-0.006687,0.962422,-0.125564,0.132531,-0.039045,0.235768
17,( C),( American ),0.156340,0.239164,0.034179,0.218620,0.914099,1.0,-0.003212,0.973708,-0.100224,0.094594,-0.027002,0.180765
18,( MANHATTAN ),( American ),0.412647,0.239164,0.129867,0.314717,1.315904,1.0,0.031177,1.110251,0.408725,0.248814,0.099302,0.428860
19,( American ),( MANHATTAN ),0.239164,0.412647,0.129867,0.543003,1.315904,1.0,0.031177,1.285246,0.315529,0.248814,0.221939,0.428860
20,( BRONX ),( B),0.095204,0.283887,0.027319,0.286950,1.010789,1.0,0.000292,1.004296,0.011797,0.077660,0.004277,0.191591
21,( B),( BROOKLYN ),0.283887,0.232744,0.066889,0.235619,1.012356,1.0,0.000816,1.003762,0.017043,0.148728,0.003748,0.261507
22,( BROOKLYN ),( B),0.232744,0.283887,0.066889,0.287395,1.012356,1.0,0.000816,1.004922,0.015907,0.148728,0.004898,0.261507
23,( Chinese ),( B),0.118038,0.283887,0.041768,0.353853,1.246459,1.0,0.008259,1.108283,0.224190,0.115972,0.097703,0.250492
24,( B),( MANHATTAN ),0.283887,0.412647,0.113671,0.400408,0.970340,1.0,-0.003475,0.979588,-0.040937,0.195021,-0.020838,0.337937
25,( MANHATTAN ),( B),0.412647,0.283887,0.113671,0.275467,0.970340,1.0,-0.003475,0.988379,-0.049467,0.195021,-0.011758,0.337937
26,( B),( QUEENS ),0.283887,0.227080,0.069120,0.243478,1.072217,1.0,0.004655,1.021677,0.094053,0.156435,0.021217,0.273933
27,( QUEENS ),( B),0.227080,0.283887,0.069120,0.304388,1.072217,1.0,0.004655,1.029472,0.087140,0.156435,0.028629,0.273933
28,( C),( BROOKLYN ),0.156340,0.232744,0.036727,0.234919,1.009349,1.0,0.000340,1.002844,0.010978,0.104233,0.002836,0.196361
29,( Chinese ),( BROOKLYN ),0.118038,0.232744,0.036076,0.305633,1.313174,1.0,0.008604,1.104972,0.270404,0.114635,0.095000,0.230319
30,( C),( MANHATTAN ),0.156340,0.412647,0.066416,0.424819,1.029499,1.0,0.001903,1.021163,0.033964,0.132153,0.020725,0.292886
31,( C),( QUEENS ),0.156340,0.227080,0.034624,0.221467,0.975284,1.0,-0.000877,0.992791,-0.029163,0.099268,-0.007261,0.186971
32,( Chinese ),( MANHATTAN ),0.118038,0.412647,0.029316,0.248362,0.601876,1.0,-0.019392,0.781431,-0.428572,0.058472,-0.279703,0.159703
33,( Chinese ),( QUEENS ),0.118038,0.227080,0.033673,0.285270,1.256255,1.0,0.006869,1.081416,0.231284,0.108118,0.075286,0.216778
34,( Italian ),( MANHATTAN ),0.047672,0.412647,0.029394,0.616597,1.494248,1.0,0.009723,1.531946,0.347325,0.068212,0.347235,0.343915
35,"( A, BROOKLYN )",( American ),0.116414,0.239164,0.025238,0.216795,0.906469,1.0,-0.002604,0.971439,-0.104566,0.076400,-0.029401,0.161160
36,"( American , BROOKLYN )",( A),0.045329,0.513081,0.025238,0.556769,1.085150,1.0,0.001980,1.098569,0.082194,0.047335,0.089725,0.302979
37,"( A, MANHATTAN )",( American ),0.214806,0.239164,0.072642,0.338177,1.413995,1.0,0.021268,1.149606,0.372880,0.190498,0.130137,0.320955
38,"( A, American )",( MANHATTAN ),0.134402,0.412647,0.072642,0.540487,1.309805,1.0,0.017182,1.278208,0.273253,0.153123,0.217655,0.358263
39,"( MANHATTAN , American )",( A),0.129867,0.513081,0.072642,0.559359,1.090197,1.0,0.006010,1.105025,0.095083,0.127374,0.095043,0.350470
40,( American ),"( A, MANHATTAN )",0.239164,0.214806,0.072642,0.303734,1.413995,1.0,0.021268,1.127722,0.384819,0.190498,0.113256,0.320955
41,"( QUEENS , American )",( A),0.040071,0.513081,0.022000,0.549014,1.070035,1.0,0.001440,1.079678,0.068183,0.041419,0.073798,0.295946
42,"( B, MANHATTAN )",( American ),0.113671,0.239164,0.033228,0.292315,1.222236,1.0,0.006042,1.075105,0.205147,0.103964,0.069859,0.215624
43,"( B, American )",( MANHATTAN ),0.061208,0.412647,0.033228,0.542860,1.315556,1.0,0.007970,1.284843,0.255504,0.075410,0.221695,0.311691
44,"( MANHATTAN , American )",( B),0.129867,0.283887,0.033228,0.255859,0.901270,1.0,-0.003640,0.962335,-0.111818,0.087320,-0.039139,0.186452

In [93]:
rules[['antecedents', 'consequents', 'support', 'confidence', 'lift']]\
    .sort_values(by='lift', ascending=False)

,antecedents,consequents,support,confidence,lift
34,( Italian ),( MANHATTAN ),0.029394,0.616597,1.494248
40,( American ),"( A, MANHATTAN )",0.072642,0.303734,1.413995
37,"( A, MANHATTAN )",( American ),0.072642,0.338177,1.413995
5,( Cafe/Coffee/Tea ),( A),0.022016,0.685432,1.335915
19,( American ),( MANHATTAN ),0.129867,0.543003,1.315904
18,( MANHATTAN ),( American ),0.129867,0.314717,1.315904
43,"( B, American )",( MANHATTAN ),0.033228,0.542860,1.315556
29,( Chinese ),( BROOKLYN ),0.036076,0.305633,1.313174
38,"( A, American )",( MANHATTAN ),0.072642,0.540487,1.309805
14,( STATENISLAND ),( A),0.021026,0.650430,1.267696
33,( Chinese ),( QUEENS ),0.033673,0.285270,1.256255
23,( Chinese ),( B),0.041768,0.353853,1.246459
42,"( B, MANHATTAN )",( American ),0.033228,0.292315,1.222236
1,( American ),( A),0.134402,0.561963,1.095273
0,( A),( American ),0.134402,0.261950,1.095273
39,"( MANHATTAN , American )",( A),0.072642,0.559359,1.090197
36,"( American , BROOKLYN )",( A),0.025238,0.556769,1.085150
26,( B),( QUEENS ),0.069120,0.243478,1.072217
27,( QUEENS ),( B),0.069120,0.304388,1.072217
41,"( QUEENS , American )",( A),0.022000,0.549014,1.070035
11,( Pizza ),( A),0.029450,0.533569,1.039931
30,( C),( MANHATTAN ),0.066416,0.424819,1.029499
9,( A),( MANHATTAN ),0.214806,0.418658,1.014568
10,( MANHATTAN ),( A),0.214806,0.520556,1.014568
21,( B),( BROOKLYN ),0.066889,0.235619,1.012356
22,( BROOKLYN ),( B),0.066889,0.287395,1.012356
20,( BRONX ),( B),0.027319,0.286950,1.010789
28,( C),( BROOKLYN ),0.036727,0.234919,1.009349
7,( Italian ),( A),0.024492,0.513772,1.001348
2,( BRONX ),( A),0.047655,0.500555,0.975588
31,( C),( QUEENS ),0.034624,0.221467,0.975284
4,( BROOKLYN ),( A),0.116414,0.500179,0.974855
3,( A),( BROOKLYN ),0.116414,0.226891,0.974855
13,( QUEENS ),( A),0.113181,0.498420,0.971425
12,( A),( QUEENS ),0.113181,0.220591,0.971425
24,( B),( MANHATTAN ),0.113671,0.400408,0.970340
25,( MANHATTAN ),( B),0.113671,0.275467,0.970340
17,( C),( American ),0.034179,0.218620,0.914099
35,"( A, BROOKLYN )",( American ),0.025238,0.216795,0.906469
16,( American ),( B),0.061208,0.255926,0.901508
15,( B),( American ),0.061208,0.215609,0.901508
44,"( MANHATTAN , American )",( B),0.033228,0.255859,0.901270
6,( Chinese ),( A),0.046264,0.391940,0.763895
8,( Latin (Cuban Dominican Puerto Rican South & ...,( A),0.020030,0.385976,0.752272
32,( Chinese ),( MANHATTAN ),0.029316,0.248362,0.601876